name: Release

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        targets: x86_64-pc-windows-gnu
        
    - name: Install cross-compilation dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y gcc-mingw-w64-x86-64
        
    - name: Build for Windows
      run: cargo build --release --target x86_64-pc-windows-gnu

    - name: Publish release (create or update, overwrite assets)
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ github.ref_name }}
        name: Release ${{ github.ref_name }}
        draft: false
        prerelease: false
        files: ./target/x86_64-pc-windows-gnu/release/pekora-bootstrapper.exe
        overwrite: true
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
